import Foundation
import SwiftUI

/// Mirrors the daemon's Workstream record (see docs/ARCHITECTURE.md > "Workstream").
///
/// The persistent on-disk shape lives in the daemon's SQLite index; this struct
/// is the wire-level representation the HTTP API serves to clients. Fields that
/// the daemon may not yet ship (current sub-goal, latest confidence, attention
/// flag) are derived projections kept here as optionals so the client can render
/// them when present and degrade gracefully when not.
struct Workstream: Identifiable, Codable, Hashable, Sendable {
    enum Status: String, Codable, Sendable, CaseIterable {
        case backlog
        case active
        case paused
        case retired

        /// Forward-compat decode: an unknown status string from a newer
        /// daemon decodes to `.active` instead of throwing, so the client
        /// keeps working when the wire enum grows underneath it.
        init(from decoder: Decoder) throws {
            let raw = try decoder.singleValueContainer().decode(String.self)
            self = Status(rawValue: raw) ?? .active
        }
    }

    let id: String                // workstream_id (slug)
    let title: String
    let createdAt: Date
    let status: Status
    let memoryPath: String?
    let sessions: [String]

    // --- projections served by the daemon's `/workstreams` endpoint for the
    // home view. Optional so the model survives a leaner response shape.
    let currentSubgoal: String?
    let latestConfidence: Double?
    let needsAttention: Bool
    /// Latest TodoWrite tool_use's todo array (Feature B). nil = the agent
    /// hasn't called TodoWrite yet on this workstream — fall back to
    /// `latestActivity` for the "Currently:" line.
    let todos: [Todo]?
    /// Humanized one-liner for the most recent tool_use event (Feature A).
    /// Used as the "Currently:" line when `todos` is nil/empty AND no
    /// `activityHeadline` has been generated yet.
    let latestActivity: String?
    /// LLM-generated, present-tense, one-sentence summary of what the agent is
    /// currently doing. Generated by the daemon's Headliner background ticker
    /// every ~30s when there are enough new events to warrant a refresh. nil
    /// when no LLM is configured or no headline has been generated yet — the
    /// "Currently:" line then falls back to `latestActivity`.
    let activityHeadline: String?
    let activityHeadlineAt: Date?
    let lastEventAt: Date?
    /// "Has a Claude Code session running right now" — derived daemon-side
    /// from the event log: latest `session_start` newer than latest
    /// `session_end`. Pure presentation signal; independent of the
    /// lifecycle `status`. Drives the awake/asleep robot mascot on the
    /// Radar grid and on AgentDetailView's header. Defaults to `true`
    /// (awake) when the daemon doesn't ship the field yet, so a pre-feature
    /// daemon doesn't make every robot look dead.
    let liveSession: Bool

    init(
        id: String,
        title: String,
        createdAt: Date,
        status: Status,
        memoryPath: String? = nil,
        sessions: [String] = [],
        currentSubgoal: String? = nil,
        latestConfidence: Double? = nil,
        needsAttention: Bool = false,
        todos: [Todo]? = nil,
        latestActivity: String? = nil,
        activityHeadline: String? = nil,
        activityHeadlineAt: Date? = nil,
        lastEventAt: Date? = nil,
        liveSession: Bool = true
    ) {
        self.id = id
        self.title = title
        self.createdAt = createdAt
        self.status = status
        self.memoryPath = memoryPath
        self.sessions = sessions
        self.currentSubgoal = currentSubgoal
        self.latestConfidence = latestConfidence
        self.needsAttention = needsAttention
        self.todos = todos
        self.latestActivity = latestActivity
        self.activityHeadline = activityHeadline
        self.activityHeadlineAt = activityHeadlineAt
        self.lastEventAt = lastEventAt
        self.liveSession = liveSession
    }

    enum CodingKeys: String, CodingKey {
        case id = "workstream_id"
        case title
        case createdAt = "created_at"
        case status
        case memoryPath = "memory_path"
        case sessions
        case currentSubgoal = "current_subgoal"
        case latestConfidence = "latest_confidence"
        case needsAttention = "needs_attention"
        case todos
        case latestActivity = "latest_activity"
        case activityHeadline = "activity_headline"
        case activityHeadlineAt = "activity_headline_at"
        case lastEventAt = "last_event_at"
        case liveSession = "live_session"
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try c.decode(String.self, forKey: .id)
        self.title = try c.decode(String.self, forKey: .title)
        self.createdAt = try c.decode(Date.self, forKey: .createdAt)
        self.status = try c.decode(Status.self, forKey: .status)
        self.memoryPath = try c.decodeIfPresent(String.self, forKey: .memoryPath)
        self.sessions = try c.decodeIfPresent([String].self, forKey: .sessions) ?? []
        self.currentSubgoal = try c.decodeIfPresent(String.self, forKey: .currentSubgoal)
        self.latestConfidence = try c.decodeIfPresent(Double.self, forKey: .latestConfidence)
        self.needsAttention = try c.decodeIfPresent(Bool.self, forKey: .needsAttention) ?? false
        self.todos = try c.decodeIfPresent([Todo].self, forKey: .todos)
        self.latestActivity = try c.decodeIfPresent(String.self, forKey: .latestActivity)
        self.activityHeadline = try c.decodeIfPresent(String.self, forKey: .activityHeadline)
        self.activityHeadlineAt = try c.decodeIfPresent(Date.self, forKey: .activityHeadlineAt)
        self.lastEventAt = try c.decodeIfPresent(Date.self, forKey: .lastEventAt)
        // Default to awake for pre-feature daemons (no field on the wire) so
        // we don't falsely accuse robots of sleeping during boot or against
        // an older daemon.
        self.liveSession = try c.decodeIfPresent(Bool.self, forKey: .liveSession) ?? true
    }
}

/// Mirrors Claude Code's TodoWrite item shape. Decoded from the daemon's
/// `todos` projection (which strips malformed rows server-side, so this stays
/// a lean Codable struct on the client).
///
/// `Identifiable` uses `content` as the id. TodoWrite items are unique by
/// slot per agent convention; if the agent ever ships duplicate contents the
/// list will collapse them — acceptable for v1, glanceable display only.
struct Todo: Codable, Hashable, Identifiable, Sendable {
    enum Status: String, Codable, Sendable {
        case pending
        case inProgress = "in_progress"
        case completed
    }

    let content: String
    let status: Status
    let activeForm: String?

    var id: String { content }
}

extension Workstream {
    var statusColor: Color {
        switch status {
        case .backlog: return .gray.opacity(0.7)
        case .active:  return .green
        case .paused:  return .yellow
        case .retired: return .gray
        }
    }

    var statusLabel: String {
        switch status {
        case .backlog: return "Backlog"
        case .active:  return "Active"
        case .paused:  return "Paused"
        case .retired: return "Retired"
        }
    }
}
